printplayer :-
    write('   ^      '),nl,
    write('  | |     ~~~~~~~~~~~~~'),nl,
    write('  |.|     | YOUR TURN |'),nl,
    write('  |.|     ~~~~~~~~~~~~~'),nl,
    write('  |:|       __ '),nl,
    write(',_|:|_,    /  ) '),nl,
    write('  (Oo     / _I_ '),nl,
    write('  |_| \\  |.| __| '),nl,
    write('     \\ \\|. |___| '),nl,
    write('      \\ /.:.\\-\\ '),nl,
    write('         |.:. /------\\ '),nl,
    write('         |___| ::oOo::| '),nl,
    write('         /   | :<_T_>:| '),nl,
    write('        |____\\   :::  / '),nl,
    write('         | |  \\   :  / '),nl,
    write('         | |   |---- '),nl,
    write('         | |   | | '),nl,
    write('        /  \\  | \\___ '),nl,
    write('         \\ /   \\_____\\ '),nl,
    write('          `'),nl.

printwolf :-
    write('                        |\\---/| '),nl,
    write('                       /  \\ /  | '),nl,
    write('                  __.-.|  / \\ / '),nl,
    write('         __ ___.-         ._. |'),nl,
    write('      .-''  ''        :     V V_/ '),nl,
    write('     / ,    .        .     | '),nl,
    write('    :  ;    :        :   _/ '),nl,
    write('    |  |   .      __:   / '),nl,
    write('    |  :   /"----"| \\  | '),nl,
    write('    \\  |\\  |      | /| |'),nl,
    write('     "" "| /       || \\ |'),nl,
    write('     | /|."        ".l \\ \\'),nl,
    write('     || ||              \\--"" '),nl,
    write('     .-"".-""'),nl.

printgoblin :-
    write('               /\\_[]_/\\'),nl,
    write('              |] _||_ [|'),nl,
    write('       ___     \\/ || \\/'),nl,
    write('      /___\\       ||'),nl,
    write('     (|   |)      ||'),nl,
    write('   __/{\\U/}\\_ ___/vvv '),nl,
    write('  / \\  {~}   / _|_  |'),nl,
    write('  | /\\  ~   /_/   []'),nl,
    write('  |_| (____)        '),nl,
    write('  \\_]/______\\       '),nl,
    write('     _\\_||_/_       '),nl,
    write('    (_,_||_,_)      '),nl.

printdragon :-
    write('                   \\||/ '),nl,
    write('                   |   \\___oo '),nl,
    write('       /\\  /\\   / (__vvvvv|| '),nl,
    write('      ) /^\\) ^\\/ _) '),nl,
    write('      )   /^\\/   _) '),nl,
    write('      )   _ /  / _) '),nl,
    write(' /\\  )/\\/ ||  | )_) '),nl,
    write('<  >      |(,,) )__) '),nl,
    write('||      /    \\)___)\\ '),nl,
    write('| \\____(      )___) )___ '),nl,
    write('\\______(_______;;; __;;; '),nl.

printsecretboss :-
    write('           ,    ,          .'),nl,
    write('           \\\\ \\\\          //'),nl,       
    write('          ) \\\\ \\\\    _p_/ /'),nl,
    write('          )^\\))\\))  /   \\/'),nl,
    write('           \\_|| || / /^`-" '),nl,
    write('  __       -\\ \\\\--/ / '),nl,
    write('<"  \\\\___/   ___. )"'),nl,
    write('     `====\\ )___/\\\\ '),nl,
    write('          //     `"'),nl,
    write('          \\\\    /  \\ '),nl,
    write('           `"'),nl.

printslime :-
    write('           .^.'),nl,
    write('         (     )'),nl,
    write('       (  \\   /  )'),nl,
    write('     (             )'),nl,
    write('   (       >0<       )'),nl,
    write('  (                    )'),nl,
    write('  (____________________)'),nl.
    
printarcher :-
    write('              /\\\\           '),nl,         
    write('            /   \\\\                         '),nl,
    write('           /     \\\\                      '),nl,
    write('      \\\\/,//      \\\\             '),nl,
    write('    __|/   |       ||            '),nl,
    write('  /,` |_  ~| >>>---`)>                '),nl,
    write('(  `---`\\--`` _,`  ||                 '),nl,
    write(' `--.    \\ ,-`    //                 '),nl,
    write('    |    \\|     //                 '),nl,
    write('    |     \\   //                 '),nl,
    write('    |_____|\\//                            '),nl,                        
    write('    |  ,  |    ~~~~~~~~~~~~~      '),nl,
    write('    | : \\ :    | YOUR TURN |                       '),nl,
    write('    | | : :    ~~~~~~~~~~~~~                        '),nl,
    write('    | | | |                            '),nl,
    write('    | | |_`.                  '),nl,
    write('    `--`        '),nl. 

printninja :-
    write('        ___ '),nl,
    write('      /_____\\   ~~~~~~~~~~~'),nl,
    write('     |       | | YOUR TURN |'),nl,
    write('     \\``````/   ~~~~~~~~~~~'),nl,
    write('     __\\   /__'),nl,
    write('   /     ,    \\'),nl,
    write('  /     ||     \\'),nl,
    write(' /  .__.||.__.  \\'),nl,
    write('(   }___||___{   )'),nl,
    write(' \\  \\|      | \\  \\'),nl,
    write('  \\  |      |  \\  \\   ^ '),nl,
    write('   `_|      |   `__)< O >'),nl,
    write('     |  /\\  |         V'),nl,
    write('     | | |  |'),nl,
    write('     | | |  |'),nl,
    write('    (__) (__)'),nl.
